export const DEFAULT_TEXT =
  'Tại huyện Cái Bè, tỉnh Tiền Giang (ĐBSCL, Việt Nam), nông dân nhỏ lẻ và hội phụ nữ phối hợp với Hợp tác xã Tân Phong để thu mua lúa thơm. Thương lái và doanh nghiệp xuất khẩu ký hợp đồng bao tiêu; cán bộ Phòng Nông nghiệp và cán bộ xã hướng dẫn kỹ thuật, còn đơn vị vận chuyển và kho trữ hỗ trợ logistics cho vùng Mekong.'

export const LABEL_OPTIONS = [
  'Farmers',
  'Commercial Farmers',
  'Smallholders',
  'Associations',
  'Cooperatives',
  'Women',
  'Youth',
  'Middlemen',
  'Traders',
  'Cooperative Management Committee',
  'Commune Officials',
  'Agriculture Department Officials',
  'Input Sellers',
  'Hired Labor / Workers',
  'Landless Farmers',
  'Wholesalers',
  'Processors',
  'Retailers',
  'Consumers',
  'Financial Institutions',
  'Transporters',
  'Storage Providers',
  'Government Organizations',
  'Non-Governmental Organizations',
  'Policy Makers',
  'Village Chiefs',
  "People's Committees",
  'Irrigation Organizations',
  'Youth Organizations',
  "Women's Organizations",
  'Policy Implementers',
  'Technicians',
  'Extensionists',
  'Commune Officers',
  'Project Officers',
  'Experts',
  'Scientists',
  'Export Companies',
  'Ethnic Minorities',
  'Khmer',
  'Cham',
  'People with Disabilities',
  'Elderly',
  'Poor Farmers',
  'Certifiers',
  'International Development Actors',
  'Donors',
  'Locations',
  'People',
  'Engineers',
  'Actors',
  'Diseases',
]

export const DEFAULT_LABELS = [
  'Smallholders',
  'Cooperatives',
  "Women's Organizations",
  'Middlemen',
  'Export Companies',
  'Commune Officials',
  'Agriculture Department Officials',
  'Storage Providers',
  'Transporters',
  'Locations',
  'People',
  'Engineers',
  'Diseases',
]

